security:

    providers:
        db:
            entity:
                class: App\Entity\User
                property: username

    firewalls:

        main:
            pattern: ^/
            provider: db
            anonymous: true
            logout_on_user_change: true # pour supprimer le deprecated warning
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: main

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    encoders:
        App\Entity\User:
            algorithm: bcrypt

